In [8]:
import pandas as pd

In [9]:
st = pd.read_csv('/home/ifmt-aluno/Downloads/cotação.csv')

In [10]:
st

         Data Valor Diário do Dólar
0    01/01/26   5,5018 (ref. 31/12)
1    02/01/26                5,4372
2    03/01/26                5,4372
3    04/01/26                5,4372
4    05/01/26                5,4351
..        ...                   ...
112  23/04/26                4,9539
113  24/04/26                5,0083
114  25/04/26                5,0083
115  26/04/26                5,0083
116  27/04/26                 4,993

[117 rows x 2 columns]

In [34]:
st.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 0 entries
Freq: D
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Data                   0 non-null      object
 1   Valor Diário do Dólar  0 non-null      object
dtypes: object(2)
memory usage: 0.0+ bytes

In [35]:
st['Data'] = pd.to_datetime(st['Data'], dayfirst= True)

In [36]:
st.set_index('Data', inplace= True)

In [37]:
st = st.asfreq('D')

In [42]:
st.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 0 entries
Freq: D
Data columns (total 1 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Valor Diário do Dólar  0 non-null      object
dtypes: object(1)
memory usage: 0.0+ bytes

In [43]:
st

Empty DataFrame
Columns: [Valor Diário do Dólar]
Index: []

In [44]:
st.dropna(inplace=True)